In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('/content/HW2_data.csv')

In [ ]:
data.head()

   Day   Outlook Temperature Humidity    Wind Decision
0    1     Sunny         Hot     High    Weak       No
1    2     Sunny         Hot     High  Strong       No
2    3  Overcast         Hot     High    Weak      Yes
3    4      Rain        Mild     High    Weak      Yes
4    5      Rain        Cool   Normal    Weak      Yes

# Naive Bayes

In [ ]:
def prob_decision(df, decision):
    return len(df[df['Decision']==decision])/len(df)

In [ ]:
def joint_prob_nb(row, df, decision):

    cols = {0: 'Day', 1: 'Outlook', 2: 'Temperature', 3:'Humidity', 4:'Wind', 5:'Decision'}
    y_filtered_df = df[df['Decision']==decision]

    prob_x = 1
    prob_xy = 1
    
    for i in range(1,len(row)-1):
        x_i_val = row[i]
        #print(cols[i])
        #prob_x[i-1] = len(y_filtered_df[y_filtered_df[cols[i]==x_i_val]])/len(y_filtered_df)
        prob_xi = len(y_filtered_df[y_filtered_df[cols[i]]==x_i_val])/len(y_filtered_df)
        #prob_xi = len(y_filtered_df[y_filtered_df['Outlook']=='Sunny'])/len(y_filtered_df)
        prob_x = prob_x * prob_xi #len(y_filtered_df[y_filtered_df[cols[i]==x_i_val]])/len(y_filtered_df)
    
    prob_y = prob_decision(df, decision)

    prob_xy= prob_x * prob_y

    return prob_xy

In [ ]:
# Naive Bayes
prob_xy_yes = []
prob_xy_no = []
map_decision = []
for i,row in data.iterrows():
  #print(row)
  prob_xy_yes.append(joint_prob_nb(row,data,'Yes'))
  prob_xy_no.append(joint_prob_nb(row,data,'No'))
  map_est = 'Yes' if prob_xy_yes[i] > prob_xy_no[i] else 'No'
  map_decision.append(map_est)

In [ ]:
df_res = data.copy()

In [ ]:
df_res['prob_xy_yes'] = prob_xy_yes
df_res['prob_xy_no'] = prob_xy_no
df_res['MAP_est'] = map_decision
df_res.head()

   Day   Outlook Temperature Humidity    Wind Decision  prob_xy_yes
0    1     Sunny         Hot     High    Weak       No     0.007055
1    2     Sunny         Hot     High  Strong       No     0.003527
2    3  Overcast         Hot     High    Weak      Yes     0.014109
3    4      Rain        Mild     High    Weak      Yes     0.021164
4    5      Rain        Cool   Normal    Weak      Yes     0.031746

In [ ]:
def calc_train_err(res_df):
    return len(res_df[res_df['Decision']!=res_df['MAP_est']])/len(res_df)

In [ ]:
calc_train_err(df_res)

0.07142857142857142

In [ ]:
df_res

,Day,Outlook,Temperature,Humidity,Wind,Decision,prob_xy_yes,prob_xy_no,MAP_est
0,1,Sunny,Hot,High,Weak,No,0.007055,0.027429,No
1,2,Sunny,Hot,High,Strong,No,0.003527,0.041143,No
2,3,Overcast,Hot,High,Weak,Yes,0.014109,0.000000,Yes
3,4,Rain,Mild,High,Weak,Yes,0.021164,0.018286,Yes
4,5,Rain,Cool,Normal,Weak,Yes,0.031746,0.002286,Yes
5,6,Rain,Cool,Normal,Strong,No,0.015873,0.003429,Yes
6,7,Overcast,Cool,Normal,Strong,Yes,0.021164,0.000000,Yes
7,8,Sunny,Mild,High,Weak,No,0.014109,0.027429,No
8,9,Sunny,Cool,Normal,Weak,Yes,0.021164,0.003429,Yes
9,10,Rain,Mild,Normal,Weak,Yes,0.042328,0.004571,Yes
10,11,Sunny,Mild,Normal,Strong,Yes,0.014109,0.010286,Yes
11,12,Overcast,Mild,High,Strong,Yes,0.014109,0.000000,Yes
12,13,Overcast,Hot,Normal,Weak,Yes,0.028219,0.000000,Yes
13,14,Rain,Mild,High,Strong,No,0.010582,0.027429,No

# Laplace correction

In [ ]:
def joint_prob_nb_laplace(row, df, decision):

    cols = {0: 'Day', 1: 'Outlook', 2: 'Temperature', 3:'Humidity', 4:'Wind', 5:'Decision'}
    y_filtered_df = df[df['Decision']==decision]

    prob_x = 1
    prob_xy = 1

    laplace_factors = [3,3,2,2]
    
    for i in range(1,len(row)-1):
        x_i_val = row[i]
        #print(cols[i])
        #prob_x[i-1] = len(y_filtered_df[y_filtered_df[cols[i]==x_i_val]])/len(y_filtered_df)
        prob_xi = (len((y_filtered_df[y_filtered_df[cols[i]]==x_i_val]))+1)/(len(y_filtered_df)+laplace_factors[i-1])
        #prob_xi = len(y_filtered_df[y_filtered_df['Outlook']=='Sunny'])/len(y_filtered_df)
        prob_x = prob_x * prob_xi #len(y_filtered_df[y_filtered_df[cols[i]==x_i_val]])/len(y_filtered_df)
    
    prob_y = prob_decision(df, decision)

    prob_xy= prob_x * prob_y
    #print(prob_xy)
    return prob_xy

In [ ]:
prob_xy_yes_laplace = []
prob_xy_no_laplace = []
map_decision_laplace = []
for i,row in data.iterrows():
  #print(row)
  prob_xy_yes_laplace.append(joint_prob_nb_laplace(row,data,'Yes'))
  prob_xy_no_laplace.append(joint_prob_nb_laplace(row,data,'No'))
  map_est = 'Yes' if prob_xy_yes_laplace[i] > prob_xy_no_laplace[i] else 'No'
  map_decision_laplace.append(map_est)

In [ ]:
df_res_LC = data.copy()

In [ ]:
df_res_LC['prob_xy_yes_LC'] = prob_xy_yes_laplace
df_res_LC['prob_xy_no_LC'] = prob_xy_no_laplace
df_res_LC['MAP_est'] = map_decision_laplace
df_res_LC.head()

,Day,Outlook,Temperature,Humidity,Wind,Decision,prob_xy_yes_LC,prob_xy_no_LC,MAP_est
0,1,Sunny,Hot,High,Weak,No,0.009298,0.020499,No
1,2,Sunny,Hot,High,Strong,No,0.005313,0.027332,No
2,3,Overcast,Hot,High,Weak,Yes,0.015496,0.005125,Yes
3,4,Rain,Mild,High,Weak,Yes,0.020661,0.015374,Yes
4,5,Rain,Cool,Normal,Weak,Yes,0.028926,0.004100,Yes

In [ ]:
calc_train_err(df_res_LC)

0.07142857142857142